version: "4.24.1"
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: nest
    networks:
      - mynetwork

  happyning:
    image: happyning:latest
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      DATABASE_URL: postgresql://root:1111@dev-db:5432/nest?schema=public
    networks:
      - mynetwork

  happyning-frontend:
      image: happyning-frontend:latest
      ports:
        - 5100:80
      networks:
        - mynetwork

networks:
  mynetwork:
    name: mynetwork
